from ninja import Schema
from pydantic import Field
from typing import Optional
from datetime import datetime

class PostSerializer(Schema):
    id: Optional[int] = None  # id is auto-generated by the database, so make it optional
    user_id: Optional[int] = None
    username: Optional[str] = None
    title: str
    caption: str
    image_url: Optional[str] = None  # Make image_url optional
    created_at: Optional[str] = Field(None, alias="createdAt")  # Automatically set by the database, so optional
    updated_at: Optional[str] = Field(None, alias="updatedAt")  # Automatically set by the database, so optional
    comment_count: Optional[int] = None

    class Config:
        # To make sure the date fields are returned as string formatted dates
        json_encoders = {
            str: lambda v: v.isoformat() if isinstance(v, datetime) else v
        }
        orm_mode = True 