# Generated by Django 5.1.3 on 2024-12-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='default title', max_length=200),
            preserve_default=False,
        ),
    ]
